---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: centos-6.4
- name: centos-5.9

provisioner:
    name: chef_zero

suites:
- name: default
  run_list:
    - "recipe[zabbix::default]"
  attributes:
- name: screen_resource
  run_list:
    - recipe[apt]
    - recipe[zabbix_test::screen_resource]
  attributes:
  excludes:
    - ubuntu-10.04
    - centos-5.9
    - centos-6.4
